#!/bin/sh

pandoc -f markdown -t latex capitalism.md -o capitalism.tex
pandoc -f markdown -t latex free_technology.md -o free_technology.tex
pandoc -f markdown -t latex Principles.md -o Principles.tex
pandoc -f markdown -t latex what_is_the_trash_wizard.md -o what_is_the_trash_wizard.tex



